name: 'Applura deploy'
description: 'GitHub action for deploying Applura projects'
inputs:
  key:
    description: 'Deploy key for applura project'
    required: true
    default: 'key'
  directory:
    description: 'The directory which will deployed to the Applura project'
    required: true
    default: './dist'
  note:
    description: 'Deploy release note'
    required: true
    default: 'GitHub action deployment'
runs:
  using: 'node20'
  main: './dist/index.js'
